vmmouse_client.h: Include xorg-server.h before xf86_OSproc.h
xf86_OSproc.h cannot be included without first including xorg-server.h.

Without this the build fails on systems with the latest glibc,
throwing this error:

In file included from /usr/include/string.h:634:0,
                 from /usr/include/xorg/os.h:53,
                 from /usr/include/xorg/misc.h:115,
                 from /usr/include/xorg/window.h:50,
                 from /usr/include/xorg/globals.h:7,
                 from /usr/include/xorg/opaque.h:34,
                 from /usr/include/xorg/xf86_OSproc.h:127,
                 from vmmouse_client.h:42,
                 from vmmouse_client.c:38:
/usr/include/xorg/os.h:579:1: error: expected identifier or '(' before '__extension__'
strndup(const char *str, size_t n);

This is caused by HAVE_STRNDUP not being set (it is set from xorg-server.h),
causing os.h to redefine it.

Signed-off-by: Stefan Dirsch <sndirsch@suse.de>
Reviewed-by: Daniel Stone <daniels@collabora.com>
Acked-by: Thomas Hellstrom <thellstrom@vmware.com>